apiVersion: v1
kind: Secret
metadata:
  name: postgres-login-pwd
type: kubernetes.io/basic-auth
# string data accepts clear text, data accepts only base64 code
stringData:
  username: pengfei
  password: foobar