apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pokemon-data-viz
spec:
  project: default
  source:
    repoURL: https://github.com/pengfei99/PokemonDataViz.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: user-pengfei
  syncPolicy:
    automated:
      selfHeal: true